services:
  backend:
    container_name: backend
    command: gunicorn visualspace.wsgi --reload --bin 0.0.0.0:8000 --threads 4 --log-file -
    build:
      context: ./back
    volumes:
      - ./back/:/app/
      - ./back/logs/:/app/logs/
    ports:
      - "8000:8000"
    env_file:
      - path: ./back/.env.dev

  frontend:
    container_name: frontend
    build:
      context: ./front
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
volumes:
  media:
  static:
