# Generated by Django 5.0.3 on 2024-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="дата обращения")),
                ("comment", models.TextField(verbose_name="комментарий к обращению")),
                ("date_updated", models.DateTimeField(auto_now=True, verbose_name="дата последнего обновления")),
                ("phone", models.CharField(max_length=15, verbose_name="телефон заказчика")),
                ("name", models.CharField(max_length=128, verbose_name="имя заказчика")),
                ("notes", models.TextField(verbose_name="заметки по заказу")),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
    ]
