# Generated by Django 5.0.3 on 2024-03-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_Appeal_model_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Web Studio \n helping startup's", max_length=64)),
                ("suptitle", models.CharField(default="Команда, понимающая ваши проблемы", max_length=64)),
                ("box_tl", models.TextField(default="Молодая \n креативная \n студия")),
                (
                    "box_tr",
                    models.TextField(
                        default="Мы - участники программы ФСИ, понимаем ваши потребности и помогаем с их закрытием"
                    ),
                ),
                (
                    "box_bl",
                    models.TextField(
                        default="Разрабатываем сайты, понимая ваши проблемы и решая их доступным способом"
                    ),
                ),
                ("box_br", models.TextField(default="Развиваем вас и ваш бренд")),
                ("advantages", models.CharField(default="Преимущества", max_length=32)),
                ("adv_1_title", models.CharField(default="Индивидуальный подход", max_length=32)),
                ("adv_2_title", models.CharField(default="Сэкономленное время", max_length=32)),
                ("adv_3_title", models.CharField(default="Качество исполнения", max_length=32)),
                ("adv_4_title", models.CharField(default="Технологичность", max_length=32)),
                (
                    "adv_1_text",
                    models.TextField(
                        default="Стремимся к тому, чтобы наше сотрудничество точно отражало ваши индивидуальные требования и предпочтения, обговариваемые в процессе онлайн встречи"
                    ),
                ),
                (
                    "adv_2_text",
                    models.TextField(
                        default="Сотрудничество с нами позволяет заказчику сосредоточиться на своем бизнесе не тратя время на создание и поддержку веб-сайта"
                    ),
                ),
                (
                    "adv_3_text",
                    models.TextField(
                        default="Предлагаем лучшее соотношение цены и качества. Создаем продукт, доступный для стартапов на разных этапах развития"
                    ),
                ),
                (
                    "adv_4_text",
                    models.TextField(
                        default="Используем современные технологии для создания интерактивных и масштабируемых сайтов, сосредоточенных на адаптацию под ваши потребности"
                    ),
                ),
                ("services_title", models.CharField(default="Услуги", max_length=16)),
                ("services_landing_title", models.CharField(default="Landing page", max_length=20)),
                (
                    "services_landing_suptitle",
                    models.CharField(
                        default="Сайт-визитка, который помогает компании рассказать о себе в одной странице",
                        max_length=80,
                    ),
                ),
                ("services_landing_o1_title", models.CharField(default="О1. Брифинг", max_length=20)),
                ("services_landing_o2_title", models.CharField(default="О2. Исследования", max_length=20)),
                ("services_landing_o3_title", models.CharField(default="О3. Дизайн", max_length=20)),
                ("services_landing_o4_title", models.CharField(default="О4. Разработка", max_length=20)),
                (
                    "services_landing_o1_text",
                    models.TextField(
                        default="Перед началом работы мы проводим с Вами брифинг, чтобы уточнить все нюансы и особенности проекта, не упустить важные детали. Это позволяет нам эффективно использовать время клиентов и сразу переходить к исследованиям."
                    ),
                ),
                (
                    "services_landing_o2_text",
                    models.TextField(
                        default="Получив от Вас необходимую информацию по проекту, мы анализируем конкурентов, удобство пользования сайтом, качество дизайна и потребности Ваших клиентов, чтобы найти оптимальные решения."
                    ),
                ),
                (
                    "services_landing_o3_text",
                    models.TextField(
                        default="на этом этапе мы разрабатываем функциональный прототип сайта, отображающий структуру контента и функционал. После утверждения этого прототипа, начинается работа над визуальным оформлением сайта, согласование с Вами его общего вида."
                    ),
                ),
                (
                    "services_landing_o4_text",
                    models.TextField(
                        default="Наша команда разработчиков преобразует веб-дизайн и утвержденный функционал в интерактивный веб-сайт с применением передовых web-технологий, таких как Vue.js, Python с Django + REST API, контейнеризация с Docker. Наш подход сосредоточен на адаптации каждого элемента к Вашим уникальным потребностям, чтобы гарантировать высокое качество и уникальный пользовательский опыт."
                    ),
                ),
                ("services_landing_note_title", models.CharField(default="Примечание:", max_length=16)),
                (
                    "services_landing_note_text",
                    models.CharField(
                        default="Итоговые сроки могут быть значительно меньше, это обговаривается с клиентом",
                        max_length=100,
                    ),
                ),
                ("services_business_title", models.CharField(default="Корпоративный сайт", max_length=32)),
                (
                    "services_business_suptitle",
                    models.CharField(
                        default="Многостраничный сайт для бизнеса, помогает рассказать о продукте", max_length=100
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="appeal",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
        migrations.AlterField(
            model_name="appeal",
            name="comment",
            field=models.TextField(verbose_name="Комментарий к обращению"),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата обращения"),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления"),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Имя заказчика"),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="notes",
            field=models.TextField(verbose_name="Заметки по заказу"),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Телефон заказчика"),
        ),
    ]
