# Generated by Django 5.0.3 on 2024-04-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_MainPageContent_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий к обращению"),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Заметки по заказу"),
        ),
    ]
